---
title: "Short Lab 4"
author: "Ziyan Zhou"
date: "8/8/2022"
output: html_document
---

These instructions correspond with the instructions from the lecture slides. See [lectures slides 8](https://svteichman.github.io/STAT302-SPR2022/files/slides/08_debuggit.html) for more information on each of these steps. 

## Part 1. Set up Git and GitHub

1. Register for a (free) [GitHub](https://github.com/) account. You may want to also add the [Student Developer Pack](https://education.github.com/pack) to your account. 

2. Install Git on your computer. 

3. Introduce yourself to Git. 

4. Introduce your computer to GitHub. 

5. Create a Git repo for Short Lab 4 and clone it to your computer. 

6. Commit a local change using the shell. 

7. Delete your local repository, then use RStudio to clone your repository back to your computer and commit a local change using RStudio. 

## Part 2. Send us your repository

Please type only the link to your repository using the template below. Fill in both the square brackets `[]` and the parentheses `()` with your link.

[https://github.com/zzyazyx/shortlab4](https://github.com/zzyazyx/shortlab4)

Here's a checklist of what we should see at the link above:

1. A `README.md` file with two lines indicating that it has been edited through shell on your local computer as well as through RStudio.
2. A `.Rmd` file for Short Lab 4.
3. A `.html` file for Short Lab 4.
